// Push settings that used to need env vars (VAPID keys, cron secret, app URL) are generated by the
// server on first use and stored in public.krob_config (service key only). Env vars still win if set.
import { randomBytes } from "node:crypto";
import webpush from "web-push";
import { admin, cronSecret, serverEnv } from "./push";

export type PushConfig = { appUrl: string | null; cronSecret: string; vapidPublic: string; vapidPrivate: string; subject: string; source: "env" | "db" };

type Row = { app_url: string | null; cron_secret: string | null; vapid_public: string | null; vapid_private: string | null };

// Public origin of the request (the URL the phone used), so the cron job knows where to call.
export function requestOrigin(req: Request): string | null {
  const host = req.headers.get("x-forwarded-host") ?? req.headers.get("host");
  if (!host || host.startsWith("localhost") || host.startsWith("127.")) return null;
  return `https://${host}`;
}

export async function getPushConfig(origin?: string | null): Promise<PushConfig | null> {
  const { env } = serverEnv();
  const db = admin();
  const { data, error } = await db.from("krob_config").select("app_url,cron_secret,vapid_public,vapid_private").eq("id", 1).maybeSingle();
  if (error) {
    // Table not created yet (old SQL): only env vars can work.
    if (env.vapidPublic && env.vapidPrivate && cronSecret()) return { appUrl: origin ?? null, cronSecret: cronSecret()!, vapidPublic: env.vapidPublic, vapidPrivate: env.vapidPrivate, subject: env.vapidSubject, source: "env" };
    return null;
  }
  const row: Row = data ?? { app_url: null, cron_secret: null, vapid_public: null, vapid_private: null };
  const patch: Partial<Row> = {};
  if (!row.vapid_public || !row.vapid_private) {
    const k = webpush.generateVAPIDKeys();
    patch.vapid_public = k.publicKey;
    patch.vapid_private = k.privateKey;
  }
  if (!row.cron_secret) patch.cron_secret = randomBytes(24).toString("base64url");
  if (origin && origin !== row.app_url) patch.app_url = origin;
  if (Object.keys(patch).length) {
    await db.from("krob_config").upsert({ id: 1, ...row, ...patch, updated_at: new Date().toISOString() });
    Object.assign(row, patch);
  }
  const useEnv = !!(env.vapidPublic && env.vapidPrivate);
  return {
    appUrl: row.app_url,
    cronSecret: cronSecret() ?? row.cron_secret!,
    vapidPublic: useEnv ? env.vapidPublic! : row.vapid_public!,
    vapidPrivate: useEnv ? env.vapidPrivate! : row.vapid_private!,
    subject: process.env.VAPID_SUBJECT?.trim() || row.app_url || "https://krob.app",
    source: useEnv ? "env" : "db",
  };
}
